### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by wilo1** [adlnet/SandboxAssetServer#2]
Hi again,
I am now trying to install the asset server as a standalone since it failed to install with the sandbox on our  digital ocean droplet running Ubuntu 14.04 x64. I was able to get the sandbox itself installed but not the integrated asset server. We are trying to get this set up for a big group of students and the use of the assetsserver is the entire reason we want to use it! It's an excellent feature. Yes, we can integrated the 3DR (and have it going) but the asset server will allow our students to upload eaiser and faster etc. Here is the error I am getting when I try to install the standalone

> sqlite3@3.1.0 install /root/SandboxAssetServer/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0

Creating a symbolic link to nodejs did not work and I had to restore the sandbox after trying that. Any help would be appreciated!

**Comment by wilo1** [comment]
Never mind, I googled it and once I used  sudo apt-get install nodejs-legacy  it worked. I may have other questions as we get this going though. Thanks!

**Comment by rchadwic** [comment]
Hey Janet. Glad you got that worked out. Since Node merged in IO.js, we're having some trouble keeping up to date. For now, the best answer is to use the older node (12.x). I think this may be worked out on its own in the future, as different packages are updated.
